# Enable GitHub Pages
theme: minima
title: "ClassFlow - Smart Timetable Management"
description: "Revolutionary freemium timetable management system for schools and institutions"
url: "https://prashant-11.github.io"
baseurl: "/TimeTablePlanner"

# SEO and metadata
author: "ClassFlow Team"
twitter:
  username: classflow
  card: summary_large_image

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Exclude files
exclude:
  - node_modules/
  - .git/
  - .gitignore
  - README.md
